@Code
    ViewData("Title") = "Ana Sayfa"
    Layout = "~/Views/Shared/_Layout.vbhtml"
End Code

<h1>Ana Sayfa</h1>

<p>
    Yalın Enstitü Derneği, profesyonel iş yaşamıyla tanışma serüvenimizde bize heyecan verici ve fırsatlarla dolu bir kapı açtı. Bu kapıdan içeri girdiğimizde ise iş yaşamına dair çok farklı, yaratıcı bakış açıları ve yaklaşımlarla karşılaştık.

    Yalın Enstitü bünyesinde bulunduğumuz süre boyunca içinde yer aldığımız öğrenme süreci hiçbir zaman duraksamaya uğramadı, aksine devamlı hızını ve verimini artırarak devam etti; ediyor da. Bu süreçle ilgili bizi en çok şaşırtan nokta ise – profesyonel iş yaşamına dair beklentilerimizden çok daha farklı olarak – Yalın Enstitü’nün iş yaşamına yaklaşımındaki normlarının merkezine öğrenmeyi almış olması oldu. Çünkü öğrenci gençler, özellikle de sosyal bilimler alanlarında okuyanlar, öğrenmenin hayatımızdaki payının okul hayatının sonlanmasının ardından oldukça azalacağına dair bir beklenti içerisindeler. Bunda ezberci eğitim sisteminin getirdiği bıkkınlığın da mutlaka payının olduğu düşünülebilir. Hâlbuki Yalın Enstitüde gördüğümüz bunun tam tersi oldu. Öğrenmenin önemini ve nasıl keyifli hale getirileceğini gördük. Bu süre zarfında öğrendiğimiz en önemli şey; insanın çalıştığı kurumda fark yaratabilmesinin, topluma ve hayata anlam katacak işler yapabilmesinin tek yolunun, daima öğrenmekten, devamlı ileri gitmeye çalışmaktan geçtiği oldu.

    Biz öğrencilerin üniversitenin son yıllarında derdine düştüğü “kariyer yapma” kavramının ise kişinin kendini bu öğrenmenin akışına kaptırmasından sonra kendiliğinden oluşmaya başlayacağını ve evrileceğini anladık. Ancak maalesef iş yaşamına atılmak üzere olan birçok genç, kariyer yapmayı ve iyi bir kazancı bir numaralı hedef haline getiriyor. Bu iki hedefin, süreci mükemmelleştirmeye odaklı bir yaşam sürdürüldüğünde kendiliğinden oluşacağını bilmek gayet huzur verici bir şey.

    Yalın Enstitüde stajyer olarak sahip olduğumuz en büyük avantajlardan biri de hem Türkçe hem İngilizce 1000’e yakın kitabımızın bulunduğu Yalın Enstitü kitaplığı. Uluslararası çapta, Yalın Düşünceyi ve iş yaşamını ilgilendiren birçok kaliteli eserin olduğu kitaplığımız birden fazla kategoriye ayrılmış durumda, bunlara örnek olarak; Yalın Teknikler, Liderlik, Kişisel Gelişim, Satış Pazarlama – Marka Yönetimi, Yönetim Bilimi, Girişim İnovasyon, Ürün Geliştirme kategorilerini verebiliriz.  Bunun yanında Yalın Düşünce kitabı da dahil olmak üzere Yalın Enstitü’nün Optimist Yayınları ile Türkçeye kazandırdığı 24 kitap bulunuyor.

    Yalın Enstitü Derneği, bünyesine kattığı herkese ilk olarak James P. Womack ve Daniel T. Jones’in kaleme aldığı “Yalın Düşünce” kitabını hediye edip, kişiden bu kitabı okumasını istiyor. Yalın düşüncenin ne olduğu, prensiplerinin nelerden oluştuğunu anlatan bu kitapta ayrıca birbirinden farklı küçük, orta ve büyük şirketlerde yalın düşüncenin nasıl uygulandığı ve alınan sonuçların ne olduğu da ayrıntılı bir şekilde anlatılmakta. Başucu kitabı niteliği taşıyan bu eser; gerçekten de yalın düşünce sistemini anlamak, dünyaya yalın gözlükle bakabilmek adına okunması gereken ilk eserdir diyebiliriz.

    Şu anda ise işletmelerde kültür anlayışının nasıl yerleşmesi ve neleri kapsaması gerektiğiyle alakalı olan, dünyanın önde gelen Toyota uzmanlarından Jeffrey K. Liker ve Michael Hoseus’un birlikte yazdığı “Toyota Kültürü” ile bir işletmede israfı ortadan kaldırmak adına yapılması gerekenlerin neler olduğunu somut örneklerle anlatan, Hiyoshi Suzaki’nin yazdığı “İmalatta Mükemmellik Yolu” adlı kitapları okumaktayız.

    Enstitüdeki birincil görevimiz ise internet sitemizi canlı tutabilmek ve insanların yalın düşünceyi daha iyi anlayabilmelerini sağlamak adına yaptığımız makale ve yazı çevirileri diyebiliriz. Küresel Yalın Ağ’ın (LGN) üyelerinden oluşan, dünyanın farklı bölgelerinde çalışan diğer yalın danışmanların çalışmalarını anlattıkları bu yazıları çevirerek hem okuyucu kitlemizi bilgilendirmiş oluyor hem de kendimizi yalın konusunda pekiştirme fırsatı buluyoruz. Yazılar; vaka analizleri, yalın düşüncenin ve uygulamalarının ayrıntılı olarak ele alınması gibi konu başlıkları etrafında dolaşmakta. Öğrenmek, fikir sahibi olmak adına birçok faydası bulunan bu yazılar, bilgilerinizi tazelemek için de iyi bir fırsat sunmakta.

    Yalın Enstitüyü farklı ve eğlenceli kılan diğer bir özelliği de çok farklı disiplinlerdeki insanları bir araya getirmesidir diyebiliriz. Uluslararası ilişkilerden, mühendisliğe ve mimariye uzanan bu disiplinler; farklı ilgi alanlarını ve bakış açılarını da bir araya getirerek yapılan çalışmaların herkes adına ufuk açıcı olma potansiyelini arttırmanın yanı sıra keyifli bir iş ve sohbet ortamı oluşturuyor.

    Dönem dönem proje olarak ihtiyaç ve pazar analizi de yapıyoruz. Müşterilerimizden gelen istekler doğrultusunda yaptığımız bu araştırmalar ile ülkemiz içeresinde farklı sektörlerin üretim kapasiteleri, ülke dışındaki ihracat potansiyelleri hakkında bilgi sahibi oluyoruz. Ayrıca analizlerin raporu yazılırken yapılan araştırmalarda sektörlerin tarihsel gelişimlerini, rakip ülkelerin durumlarını öğrenerek, diğer bir deyişle küçük anekdotlarla, dünyanın mevcut durumu hakkında daha bütünsel bir fikre sahip olabiliyoruz.

    Son olarak değinmemiz gereken kişi ise tüm bu imkânları bize sağlayan Sayın Yalçın İpbüken olmalı. Hayatı boyunca ülkemize hizmet etme bilinciyle çalışmış ve hala da çalışmaya devam etmekte olan Yalçın Bey, sahip olduğu bu bilinçle yeni nesli yetiştirmeyi de önemli bir yere konumlandırmış durumda. Bunun en somut örneği ise zamanında İ.D.E.A. A.Ş. İK Departmanında görev yapan ve şu anda Koç Üniversitesinde İK Direktörü olarak çalışmakta olan Mahide Sondikme’nin Yalçın Bey’e teşekkür için geldiği gündür diyebiliriz. Beraber çalıştığı insanların kişisel ve mesleki gelişimlerini gururla takip eden Yalçın Bey için son derece mutluluk verici bir gündü. Bunların yanı sıra Yalçın Bey yaptığı toplantılara stajyerleri de dahil ederek bizlere profesyonel bir çalışma ortamının nasıl olması gerektiğini göstermekte ve bizlerle olan iletişimi sırasında fikir alışverişini esas almakta. Yalçın Bey ile beraber çalışmak bize şunları öğretti diye madde madde saymak için henüz erken sayılabilir ancak ileride çok faydasını göreceğimiz bir bakış açısının tohumlarının zihnimizde yeşermesine yardımcı olduğundan eminiz.

    Tüm bunlara ek olarak, staj mülakatından bu yana bizlere eşsiz bir şekilde değer veren ve bu fırsatları sunan Yalın Enstitü’nün değerli insanlarına teşekkür etmeyi de borç biliriz. Bir gün güzel Türkiye’mizin tüm işletmelerinde öğrenmenin çekirdek unsur olarak yer edinmesi dileğiyle…
</p>

